apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-v2-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-v2
  template:
    metadata:
      labels:
        app: client-v2
    spec:
      containers:
        - name: client-v2
          image: abdessalamwizli/client-v2:d1fc2b7-dirty
          imagePullPolicy: IfNotPresent
          env:
            - name: CLUSTER_URL
              value: 'http://ingress-nginx-controller.ingress-nginx.svc.cluster.local'
            - name: INGRESS_HOST
              value: 'ticketing.dev'
---
apiVersion: v1
kind: Service
metadata:
  name: client-v2-srv
spec:
  selector:
    app: client-v2  
  ports:
    - name: client-v2
      protocol: TCP
      port: 3000
      targetPort: 3000
